### ISSUE TITLE
Some questions about global sources

### ISSUE THREAD

**Issue by paul-lrr** [xjsframework/xjs#109] opened 2016-07-18 17:13 UTC
Not exactly a specific "Issue", but I didn't see anywhere else to ask. Let me know if there is a better place to put this.

I have been experimenting with Global Sources and there is definitely some interesting potential there, but the connection between the Items seems a little fragile. If the "Keep source in memory" box is ever unchecked, the connection is permanently lost. Is there a way to "reconnect" Items to a Source so that they are kept in sync again? Or do you have to delete the Item and recopy it? Also, is there a way to create a global source via the API? ie. make a new Item based on an existing source?

Obviously the transition from individual Sources to multiple Items with a single Source (and the accompanying API changes) has been a little confusing. Would it make sense to, instead of deprecating it, have the Source class refer to the underlying Source with all the properties and methods that are applied globally (Source type, Source id, Item list, saveConfig() etc.) and then have the Item class refer to the properties that are Item specific (size, position, name, Item id, etc)? At the moment, the Item object can affect both the current Item or the underlying Source depending on what functions are used. By the same token, `Scene#getSources` is currently deprecated in favor of `Scene#getItems`, but it seems like getting the Sources in the Scene and getting the Items in a Scene should be separate and are both potentially useful functions. Having `getItems` return a list of Sources that you then have to individually parse with `getItemList` just adds to the confusion.

**Comment by Matrim-Cauthon** [comment] 2016-07-19 07:27
Thanks for asking those questions! This is definitely the right place to ask.

1. Currently there is no way to "reconnect" back to a global source; the only way to do it is to recopy one of the items linked to the global source.
2. We don't have a way to "clone" a global source's item yet. With issues such as #107 already in the pipeline, we should definitely revisit the basics of item manipulation.
3. I definitely agree that the changes in the API (as well as the documentation) are confusing. I believe that the original justification for the current structure is the fact that under the hood, any properties that don't belong to the `Item` are actually "bubbled up" to the `Source`. Currently there are very few properties that belong to the source (biggest of which is source configuration object from saveConfig), but mirroring the existence of both Sources and VideoItems in the API is worth looking into if it makes it easier to use.

@dcefram @SML-MeSo @virn we'll need to have some in-depth discussion about the above issues. For the time being, let's leave this issue open until we can reasonably address the different points raised.

**Comment by paul-lrr** [comment] 2016-07-19 18:02
Another question about Global Sources: I know that the config object set by `item#saveConfig` is shared by all the Items that share a global source, but is there an event that fires when the config object changes that the other instances can listen to? For example, say I have a custom plugin that just displays some text which is set in the props window. When I change the text, it is saved via `requestSaveConfig(data)` which fires the `save-config` event and then the Item saves the data with `saveConfig(data)`. If this is a global source, how do I tell the other Items that their config has changed and the text should be updated?

**Comment by paul-lrr** [comment] 2016-07-20 04:22
Ok, I see now that how Global Sources work makes the above question moot :) I thought that the global sources were syncing properties between the items. I didn't realize the the items are actually just views of the same embedded browser (or video, image, etc). That is neat!

**Comment by Matrim-Cauthon** [comment] 2016-07-20 06:41
You hit the nail on the head! I like to think of it as the "source" being some camera/game/HTML/etc that exists outside of a scene, but having multiple projections in one or more scenes (the "video items").

Which does actually lead to some weird things, such as an inability to "get the current item where the JS is executing." This is because all JavaScript is executing from the source level. The renderer part has nothing to do with JS.

In any case, if you run into more interesting use cases with regards to global sources, we'd love to know how you use them or what kind of problems the framework has when handling them.

**Comment by paul-lrr** [comment] 2016-07-20 14:15
I feel like it would be useful to have a definitive list of which properties are Item level and which are Source level. For instance, position, cropping and rotation are applied to the Items individually, but what about HTML-specific properties like browserTransparent, customCSS and BrowserCustomSize?

As a side note, there seems to be an issue with the default Text Source plugin where if you check the Keep in Memory box, it behaves as if BrowserCustomSize has been set to the item's current size and the text just distorts if you try to scale the item to reveal a longer word. I mention it here, because I suspect it might be to do with the item how the Keep in Memory setting relates to an item becoming a Global Source.

**Comment by Matrim-Cauthon** [comment] 2016-07-20 15:16
We have a small table in our documentation as to which properties are on the item level; everything else is source-level. That said, we are still working to improve the docs on that :)

@SML-MeSo could you shed some more light here about global sources and browser size? I believe there is some magic under the hood that relates specifically to the Text Source.

**Comment by SML-MeSo** [comment] 2016-07-20 17:36
Yes, I think a really in-depth discussion on global sources and item-level and source-level properties will help. As @Matrim-Cauthon has said, the nearest documentation we have for this is in this link http://xjsframework.github.io/tutorials.html#/sourceplugins where we can find the table for Rendering properties. This also corresponds to the item-level properties but I think we can improve it. As a side note, on the source properties dialog(window), the last three tabs (color, layout, effects) pertain to the item-level properties and the main tab (first tab, i.e. media, html, screen) deals with source-level properties.

As for the BrowserCustomSize "issue", this happens for all CEF sources (html and swf), and not just the Text source. CEF sources are free-sizing sources. They have no native resolution unlike media sources (video or pic dimensions), game and skype source (game/skype resolution), camera sources (video output resolution), screen/window capture (based on capture boundary), etc. Thus, the resolution/size of the CEF instance (the source) depends on the size the videoitem has at the stage. Now, following this pattern, this complicates things for global sources, wherein a single source can have multiple videoitems linked to it, thus the source wouldn't know on which videoitem it will get its browser size. To avoid this complication, when setting a CEF source as global, XBC also automatically sets the BrowserCustomSize of the source from the current size in the stage of the original videoitem so it won't matter how videoitems are to be connected to it, and whatever their sizes maybe. And yes, checking "Keep source in memory" makes a source global, so basically, you need to really set your original videoitem's size first before checking it.

Note: Unchecking "Keep source in memory" not only disconnects an item, but also resets the BrowserCustomSize.

**Comment by paul-lrr** [comment] 2016-07-20 22:31
Another issue I just ran into is that even though the instances of a Global Source appear identical, the first one seems to have a special significance. 

When I have a HTML Source by itself, I can use `xjs.Item.getItemList()` and then access the first index in the array to get the Item. If I check `Keep in Memory` to make it a Global Source and then copy it a few times, `xjs.Item.getItemList()` called from any of the Items returns the full list of Items associated with the Source. I can also delete any of the copies and `xjs.Item.getItemList()` continues to work as expected. The problem arises if I delete the *original* item (ie. the first one which I copied to make the other instances). With the original Item gone, the rest of the Items still stay in sync as they should but now `xjs.Item.getItemList()` called from any of the Items stops working (it appears that the promise is never returned) so I can't actually manipulate the Items. I expected the Items to be like hard links in a file system, where each one is an equal peer, pointing to the same Source, but it seems like the original Item has some kind of special connection to the Global Source that the copies lack.

**Comment by SML-MeSo** [comment] 2016-07-27 13:53
confirmed the issue regarding getItemList and the deleted initial item. This is due to the native itemlist API from XBC not being updated if the deleted item is attached manually to the source*. The native itemlist returned only gets updated if the videoitem is detached or not really attached from the beginning. This causes the getItemList not to resolve since the framework expects the id to be also present in the presentation. Resolution is to remove this expectation and check for rejection.

*by calling AttachVideoItem1 or AttachVideoItem2. Note that this is an internal API and a different concept from being "linked" to it. The framework automatically calls this whenever we access an item's property but only if it is not previously attached (see issue #112 ). We also do not detach it right after every call to prevent unnecessary overhead, especially when successively accessing different properties of an item.

**Comment by SML-MeSo** [comment] 2016-11-21 09:39
closing this item as most, if not all of the questions and inquiries have been addressed and looked into, including a fix on the reported bug on `xjs.Item.getItemList()`

**Closed by SML-MeSo** 2016-11-21 09:39 UTC
Labels: bug, question, ready-for-release
