### ISSUE TITLE
setSourceOrder causes error

### ISSUE THREAD

**Issue by LtSquigs** [xjsframework/xjs#87] opened 2016-03-25 06:41 UTC
Trying to use setSourceOrder, with an array of IDs, on a scene object causes the error

"Uncaught ReferenceError: SourcesListUpdate is not defined"

and the sources dont seem to get changed.

Can't find specific code thats causing this, may be a bug in XSplit itself?

**Comment by dcefram** [comment] 2016-03-25 06:59
`Uncaught ReferenceError: SourcesListUpdate is not defined` is not really a bug, it's just an 'event' of some sort that notifies the plugin that the sources list order has been updated. Just adding a dummy `window.SourcesListUpdate` would suffice (I'll add that up on the generator-xjs too, I missed that out).

I tested setSourceOrder on my end, and it works. Could you try adding up a catch statement after setSourceOrder to check out if it's throwing up some error message?

```javascript
scene.setSourceOrder(sourcesArray).catch(function(error) {
  console.error(error.message);
});
```

Please do take note that setSourceOrder will not work in source plugins. It will only work on Extension Plugins and in the Source Props window.

**Comment by LtSquigs** [comment] 2016-03-25 18:34
Ah thanks that did get rid of the spurious error.

I managed to get it working, I think it was because I was using an old layout, and for some reason it couldn't handle changing the order of the sources in that layout (maybe due to it being old or other reasons!), but creating a new layout from scratch seems to make it work like expecfted

**Comment by dcefram** [comment] 2016-03-26 02:34
Good to hear that it works right now. But I'm still curious as to what made it not work (Couldn't reproduce it on my end :( ). Please do file a issue if in case it does not work again. What I'm suspecting though is that 'probably' some of the item IDs on the array did not exist anymore in the stage. We would still want to know the exact steps to reproduce the issue so that we could investigate it (if framework bug or an issue with XSplit Broadcaster)

**Comment by Matrim-Cauthon** [comment] 2016-03-28 07:38
Yep, `SourcesListUpdate` is an event which is currently unhandled but may be ignored safely. There are a couple of other similar events which are available to Extensions if necessary.

Looks like the original issue was resolved, so I'll be closing this item. :relieved:

**Closed by Matrim-Cauthon** 2016-03-28 07:38 UTC
Labels: question
